{% set name = "PyMUMPS" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  fn: {{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f290ec4850098f108fb91cb9e7fa07302ebf5076e4329f8e6ea4924de8ba35df

build:
  number: 1007
  script: |
    pip install . -vv --global-option="build_ext" \
       --global-option="-I$PREFIX/include" \
       --global-option="-L$PREFIX/lib"
  skip: true  # [win]
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - python
    - mumps-mpi
    - mumps-include
    - setuptools
    - mpi4py
    - pip
  run:
    - python
    - scipy
    - setuptools
    - mumps-mpi
    - mpi4py
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mumps

about:
  home: https://github.com/PyMUMPS/pymumps.git
  license: BSD-3
  license_file: COPYING
  summary: 'PyMUMPS: Python parallel sparse direct solver'

extra:
  recipe-maintainers:
    - santiagoropb
    - sdrave
